### ISSUE TITLE
Мерцает LED Panel 16x16 при использовании db.begin();   

### ISSUE THREAD

**Issue by Striagor** [GyverLibs/GyverDB#3]
Делаю светофор с использованием платы WT32-S1. и LED панелью гибкой 16x16 пикселей 
![2024-11-27_17-34-26](https://github.com/user-attachments/assets/a1f36563-cdae-4da9-8b59-f0898ab15aa0)

по библиотекам:
`
#include <GyverDBFile.h>
#include <LittleFS.h>
#include <SettingsAsync.h>  
#include <ETH.h>
#include "button.h"
#include "IRremote.h"
#include <SPI.h>
#include <Adafruit_GFX.h>
#include <Adafruit_NeoMatrix.h>
#include <Adafruit_NeoPixel.h>

// настройки led панели
#define PIN        33       // Пин для управления RGB панелью 14
#define MW         16       // Ширина rgb пенели (колличество пикселей)
#define MH         16       // Высота rgb пенели (колличество пикселей)
#define BRIGHTNESS 20       // Яркость панели
#define DELAY_SHOW 5000     // Задержка 
Adafruit_NeoMatrix *matrix = new Adafruit_NeoMatrix(MW, MH, PIN, NEO_MATRIX_BOTTOM + NEO_MATRIX_RIGHT + NEO_MATRIX_COLUMNS + NEO_MATRIX_ZIGZAG, NEO_GRB + NEO_KHZ800);`

код в котором происходит глюк/мерцание
`void Init_DataBase(){
    // запуск файловой системы
    #ifdef ESP32
      LittleFS.begin(true); // format on fail
    #else
      LittleFS.begin();
    #endif

    // запуск БД и чтение из файла 
    db.begin();   
    // инициализация БД начальными значениями
    db.init(keys::wifi_ssid, "WiFiName");
    db.init(keys::wifi_pass, "pass");
    // посмотрим что записалось
    db.dump(Serial);
}`

проблема заключается в том что при использовании данных библиотек, у меня возникает мерцание на led панели раз в 3 секунды, мультиметр мне говорит что на пине который отправляет данные в led панель происходит просадка раз в 3 секунды, как только я комментирую строку db.begin();  , то мерцание проходит, но оно также проявляется в момент когда я захожу в веб интерфейс  в раздел ввести пароль для авторизации и мерцает когда я выхожу из этого раздела, подскажите как решить данную проблему и с чем она может быть связана?

**Comment by GyverLibs** [comment]
Вывод на ленту где и как организован?

**Comment by Striagor** [comment]
> Вывод на ленту где и как организован?

на момент последних тестов был подключен 33 пин, он на самой плате подписан как rs485, также добавлю что пробовал многие пины, везде ситуация одинаковая, пробовал пины ( 2,4,14,15,32,23,33,17... )

**Comment by GyverLibs** [comment]
Часть программы, где обновляется лента

**Comment by Striagor** [comment]
> Часть программы, где обновляется лента

void setup() {
    Serial.begin(115200);
    Serial.println();   
    
    matrix->begin();
    matrix->setBrightness(BRIGHTNESS);
    matrix->show();
}

void display_fillMatrix(uint16_t color) { 
  matrix->fillRect(0,0, MW, MH, color);
  matrix->show();
}

вызов функции происходит по надобности, не чаще чем раз в 100 мс, а то и реже

**Comment by GyverLibs** [comment]
Так, а что представляет собой мерцание?

**Comment by Striagor** [comment]
> Так, а что представляет собой мерцание

**Comment by GyverLibs** [comment]
Ladno

**Comment by Striagor** [comment]
> Так, а что представляет собой мерцание?

так... сегодня снова искал проблему и понял что в целом мерцание еще возможно происходит из за многопоточности

есть три потока 
  xTaskCreatePinnedToCore( Task_SwitchModeLight, "Task_SwitchModeLight",  5000, NULL, 2,  &Task1, 1);       
  delay(500); 

  xTaskCreatePinnedToCore(Task_IRRemoteControl, "Task IRRemoteControl", 5000, NULL, 2, &Task2, 1);        
  delay(500); 
  
  xTaskCreatePinnedToCore(Task_UpdateRGBPanel, "Task UpdateRGBPanel", 5000, NULL, 1, &Task3, 0);        
  delay(500); 
  
  так вот если использовать вместо xTaskCreatePinnedToCore(Task_UpdateRGBPanel...
  
 другую библиотеку многопоточности (псевдо многопоточность) 
 #include <Thread.h>  //ArduinoThread
 Thread thread_UpdateRGBPanel = Thread(); // создаём поток обновления rgb панели
 void setup() {
    ...
    thread_UpdateRGBPanel.onRun(updateRGBPanel);     // назначаем потоку задачу
    thread_UpdateRGBPanel.setInterval(0.02);  // задаём интервал срабатывания, мсек
    ...
}

void loop() {
    // обработчик UI
    sett.tick();
    if (thread_UpdateRGBPanel.shouldRun()) thread_UpdateRGBPanel.run(); // запускаем поток
}

в целом возможно проблема и не с библиотекой GyverDBFile

**Comment by GyverLibs** [comment]
DB здесь вообще последнее из за чего может быть проблема)

**Comment by Striagor** [comment]
> DB здесь вообще последнее из за чего может быть проблема)

есть теория о том что в момент отправки шим сигнала по обновлению светодиодов на панели, поток прерывается и отдается приоритет на выполнения других операций, как бы принудительно заставить выполнить функцию до конца и только после этого отдать ресурсы цп на выполнения других операций...

**Comment by GyverLibs** [comment]
Не использовать ртос или наоборот изучать его подробнее)

**Comment by Striagor** [comment]
> Не использовать ртос или наоборот изучать его подробнее)

пойду изучать его, спасибо за отклик)

**Comment by Striagor** [comment]
может кому пригодится, решение своей проблемы нашел в руководстве FreeRTOS 
https://narodstream.ru/esp32-urok-14-freertos-myuteksy/

Проблема была в многопоточности, а именно в неправильной организации, другие потоки прерывали поток в котором происходило обновление RGB панели, когда стал использовать мьютекс для обновления RGB панели, все баги прошли

**Comment by GyverLibs** [comment]
ну во
